### PR TITLE
Name cleanup

### PR DESCRIPTION
**Pull request by uniquepointer**
Internal name cleanup.

### CODE REVIEW

**Comment by crizan** [comment]
So, I noticed this only now, I had notifications a little messed up.

My main problem with the name change is that it will break some stuff from users (totally my fault, I should have done it from the start)

**Comment by uniquepointer** [comment]
Well, how would you like to proceed? Should I cancel the PR or if you want me to change things just list them and i'll get to it!

**Comment by crizan** [comment]
While changing some names should be possible without problems it would just make less sense. I'll think about doing this if I really have to break stuff (I doubt).

I think it would make sense to close this

**Comment by uniquepointer** [comment]
Alright, thank you very much for looking at it!

**Pull request closed without merging**
